Repository TeamNADA/NADA-iOS-ForRelease, pull requests merged in 2021-11, with the labels that each got.

#50 [FEAT] #49 - Moya 서버통신 구축
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Constants/URL.swift
  NADA-iOS-forRelease/Sources/AppModel/CardList/CardListDataModel.swift
  NADA-iOS-forRelease/Sources/Models/TempModel.swift
  NADA-iOS-forRelease/Sources/Network/TempNetwork.swift
  NADA-iOS-forRelease/Sources/NetworkModel/GenericResponse.swift
  NADA-iOS-forRelease/Sources/NetworkModel/NetworkResult.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupService.swift
  NADA-iOS-forRelease/Sources/NetworkService/Plugin/MoyaLoggerPlugin.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserSevice.swift
  NADA-iOS-forRelease/Sources/NetworkService/Util/UtilAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Util/UtilService.swift
  Podfile.lock
Labels: Hyungyu 🐯, Feat

#52 [ADD] #51 - http 서버통신, baseURL 설정
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Info.plist
  NADA-iOS-forRelease/Resouces/Constants/URL.swift
Labels: Hyungyu 🐯, Add

#55 [FEAT] #53 - 명함 생성, 명함 세부 조회 서버통신
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Sources/Group/ChangeGroupRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/Card.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardCreationRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/GenericResponse.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupService.swift
  NADA-iOS-forRelease/Sources/NetworkService/Plugin/MoyaLoggerPlugin.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift
Labels: Hyungyu 🐯, Feat

#59 [ADD] #57 - IQKeyboardManager 라이브러리 추가 및 설정
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift
  Podfile
  Podfile.lock
Labels: Hyungyu 🐯, Add

#62 [FEAT] #54 - 로그인, 메인, 리스트 서버통신
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardListEditRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardListLookUpRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardListRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/MainListRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/ChangeGroupRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/User/User.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserSevice.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
  Podfile.lock
Labels: Minjae 🐻‍❄️, P1 / Priority High, Feat

#64 [FEAT] #63 - 회원 관련 추가 서버 구축
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Sources/NetworkModel/User/UserWithTokenRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/User/Users.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserSevice.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
Labels: Minjae 🐻‍❄️, Feat

#60 [FEAT] #56 - 명함 그룹 뷰 서버통신
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Sources/NetworkModel/Group/CardAddInGroupRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/CardListRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/CardsInGroupResponse.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/GroupAddRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/GroupEditRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/Groups.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
Labels: Yijoon 🐨, Feat

#65 [FEAT] 명함생성 버튼활성화,뒷면 작성 구현(#58)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease.xcodeproj/xcshareddata/xcschemes/NADA-iOS-forRelease.xcscheme
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/closeBlack.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Resouces/Storyboards/CardCreation/CardCreation.storyboard
  NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCollectionViewCell.xib
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/RequiredFlavor/RequiredFlavorCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/RequiredFlavor/RequiredFlavorCollectionViewCell.xib
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardCreationRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/CardListInGroupRequest.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupService.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserSevice.swift
  NADA-iOS-forRelease/Sources/NetworkService/Util/UtilAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Util/UtilService.swift
  NADA-iOS-forRelease/Sources/Protocols/BackCardCreationDelegate.swift
  NADA-iOS-forRelease/Sources/Protocols/FrontCardCreationDelegate.swift
  NADA-iOS-forRelease/Sources/Protocols/TempProtocols.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
Labels: Hyungyu 🐯, Feat

#69 [FEAT] #68 - 바뀐 레이아웃 수정 작업
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconHome.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconHome.imageset/iconHome.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconHome.imageset/iconHome@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconHome.imageset/iconHome@3x.png
  NADA-iOS-forRelease/Resouces/Constants/Storyboard.swift
  NADA-iOS-forRelease/Resouces/Constants/ViewController.swift
  NADA-iOS-forRelease/Resouces/Storyboards/CardList.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/CustomTabBar.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/Group/Group.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/Login.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/Main/Front.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/More/More.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/TabBar.storyboard
  NADA-iOS-forRelease/Sources/AppModel/CardList/CardListDataModel.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/CardList/CardListTableViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardList/CardListTableViewCell.xib
  NADA-iOS-forRelease/Sources/Cells/MoreList/MoreListTableViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/MoreList/MoreListTableViewCell.xib
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CommonBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CustomTabBar/CustomTabBarController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/TabBar/TabBarViewController.swift
  NADA-iOS-forRelease/Sources/Views/CustomTabBar/CustomTabBar.swift
  NADA-iOS-forRelease/Sources/Views/CustomTabBar/CustomTabBarButton.swift
  NADA-iOS-forRelease/Sources/Views/CustomTabBar/CustomTabIndicatorView.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Feat, Design

#70 [REFACTOR] #61 - NetworkModel 옵셔널변수 설정 및 예외처리
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Sources/NetworkModel/Card/Card.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/CardAddInGroupRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/CardsInGroupResponse.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/GroupAddRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/GroupEditRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/Groups.swift
  NADA-iOS-forRelease/Sources/NetworkModel/User/User.swift
Labels: Hyungyu 🐯, Refactor

#77 [FEAT] #73 - 명함생성 미리보기 뷰 만들기
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Constants/Storyboard.swift
  NADA-iOS-forRelease/Resouces/Constants/ViewController.swift
  NADA-iOS-forRelease/Resouces/Storyboards/CardCreation/CardCreationPreview.storyboard
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.xib
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardCreationRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/CardsInGroupResponse.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
Labels: Hyungyu 🐯, P1 / Priority High, Feat

#83 [CHORE] #82 - 다크모드 대응 컬러 변경
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/background.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/quaternary.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/secondary.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/tertiary.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Extensions/UIColor+Extension.swift
  NADA-iOS-forRelease/Resouces/Storyboards/CardList.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/Main/Front.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/More/More.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/TabBar.storyboard
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/CardList/CardListTableViewCell.xib
  NADA-iOS-forRelease/Sources/Cells/MoreList/MoreListTableViewCell.xib
Labels: Minjae 🐻‍❄️, P1 / Priority High, Chore

#84 [FEAT] #46 - 명함 그룹화면 구현
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Constants/Storyboard.swift
  NADA-iOS-forRelease/Resouces/Constants/ViewController.swift
  NADA-iOS-forRelease/Resouces/Constants/Xib.swift
  NADA-iOS-forRelease/Resouces/Storyboards/Group/Group.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/Group/QRScan.storyboard
  NADA-iOS-forRelease/Sources/Cells/GroupCell/CardInGroupCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/GroupCell/CardInGroupCollectionViewCell.xib
  NADA-iOS-forRelease/Sources/Cells/GroupCell/GroupCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/GroupCell/GroupCollectionViewCell.xib
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddWithIdBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardResultBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CommonBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/QRScanViewController.swift
Labels: Yijoon 🐨, Feat

#90 [FIX] #89 - 카드 셀 뒷면 수정 & bottomSheet 수정
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/quaternary.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/secondary.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Extensions/UIColor+Extension.swift
  NADA-iOS-forRelease/Resouces/Storyboards/Group/GroupEdit.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/More/More.storyboard
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/GroupCell/CardInGroupCollectionViewCell.xib
  NADA-iOS-forRelease/Sources/Cells/GroupEdit/GroupEditTableViewCell.xib
  NADA-iOS-forRelease/Sources/Cells/MoreList/MoreListTableViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/MoreList/MoreListTableViewCell.xib
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CommonBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/GroupEditViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
Labels: Minjae 🐻‍❄️, Fix

#93 [FIX] #87 - 명함 그룹 화면 수정
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconFolder.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconFolder.imageset/iconFolder-1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconFolder.imageset/iconFolder@2x-1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconFolder.imageset/iconFolder@3x-1.png
  NADA-iOS-forRelease/Resouces/Storyboards/Group/Group.storyboard
  NADA-iOS-forRelease/Sources/Cells/GroupCell/CardInGroupCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/GroupCell/GroupCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
Labels: Yijoon 🐨, Fix

#95 [CHORE] #94 - 앱 로고 추가
  NADA-iOS-forRelease/Info.plist
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/AppIcon.appiconset/1024.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/AppIcon.appiconset/120(2).png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/AppIcon.appiconset/120.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/AppIcon.appiconset/180.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/AppIcon.appiconset/40.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/AppIcon.appiconset/58.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/AppIcon.appiconset/60.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/AppIcon.appiconset/80.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/AppIcon.appiconset/87.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  NADA-iOS-forRelease/Resouces/Extensions/UIViewController+Extension.swift
  NADA-iOS-forRelease/Sources/Cells/MoreList/MoreListTableViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/MoreList/MoreListTableViewCell.xib
Labels: Minjae 🐻‍❄️, 🚨review required🚨, Chore

#97 [FEAT] #85 - ID로 명함 추가 바텀 시트
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Constants/ViewController.swift
  NADA-iOS-forRelease/Resouces/Constants/Xib.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddWithIdBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardResultBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CommonBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/Views/CardView.swift
  NADA-iOS-forRelease/Sources/Views/CardView.xib
  NADA-iOS-forRelease/Sources/Views/TempViews.swift
Labels: Yijoon 🐨, Feat

#100 [CHORE] #99 - Development Team 수정
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Info.plist
Labels: Yijoon 🐨, Chore

#98 [FEAT] #91 - 다크, 라이트 모드는 일단 시스템 따라가기로
  NADA-iOS-forRelease/Info.plist
  NADA-iOS-forRelease/Resouces/Extensions/UIViewController+Extension.swift
  NADA-iOS-forRelease/Resouces/Storyboards/More/More.storyboard
  NADA-iOS-forRelease/Sources/Cells/MoreList/MoreListTableViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/MoreList/MoreListTableViewCell.xib
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/TabBar/TabBarViewController.swift
Labels: Minjae 🐻‍❄️, Feat
