Repository TeamNADA/NADA-iOS-ForRelease, pull requests merged in 2021-12, with the labels that each got.

#102 [FEAT] #88 - 명함생성뷰에서 피커뷰로 생년월일, mbti 설정
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Resouces/Extensions/UIViewController+Extension.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.xib
  NADA-iOS-forRelease/Sources/Protocols/CardCreation/BackCardCreationDelegate.swift
  NADA-iOS-forRelease/Sources/Protocols/CardCreation/FrontCardCreationDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectBirthBottomViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectMBTIBottomViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift
Labels: Hyungyu 🐯, Feat

#104 [FEAT] #103 - image picker 적용 및 명함배경 고르기 구현
  NADA-iOS-forRelease/Info.plist
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/Background/BackgroundCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/Background/BackgroundCollectionViewCell.xib
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/GroupCell/CardInGroupCollectionViewCell.xib
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift
Labels: Hyungyu 🐯, P1 / Priority High, Feat

#108 [FEAT] #96 - QR스캔 뷰 구현
  NADA-iOS-forRelease/Info.plist
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconQRClear.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconQRClear.imageset/iconQRClear.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconQRClear.imageset/iconQRClear@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconQRClear.imageset/iconQRClear@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/subtract.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/subtract.imageset/subtract.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/subtract.imageset/subtract@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/subtract.imageset/subtract@3x.png
  NADA-iOS-forRelease/Resouces/Extensions/UIViewController+Extension.swift
  NADA-iOS-forRelease/Resouces/Storyboards/Group/QRScan.storyboard
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/QRScanViewController.swift
Labels: Yijoon 🐨, Feat

#109 [FIX] #107 - BackCardCell initCell() 간소화 및 카드셀 레이아웃 수정
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/GroupCell/CardInGroupCollectionViewCell.xib
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
Labels: Hyungyu 🐯, Fix

#110 [FIX] #107 - FrontCardCell 레이아웃 수정
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.xib
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
Labels: Fix

#112 [FEAT] #91 - 시스템 무시, 스위치 값에 따른 다크모드 변경 기능 구현
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Info.plist
  NADA-iOS-forRelease/Resouces/Constants/UserDefaults.swift
  NADA-iOS-forRelease/Resouces/Storyboards/Login.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/More/More.storyboard
  NADA-iOS-forRelease/Sources/AppDelegate.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
  Podfile
  Podfile.lock
Labels: Minjae 🐻‍❄️, Feat

#115 [FEAT] #111 - [FEAT] 온보딩 레이아웃 및 화면전환 구현
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/buttonStartImg.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/buttonStartImg.imageset/buttonStartImg.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/buttonStartImg.imageset/buttonStartImg@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/buttonStartImg.imageset/buttonStartImg@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/onboarding01.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/onboarding01.imageset/onboarding01.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/onboarding01.imageset/onboarding01@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/onboarding01.imageset/onboarding01@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/onboarding02.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/onboarding02.imageset/onboarding02.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/onboarding02.imageset/onboarding02@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/onboarding02.imageset/onboarding02@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/onboarding03.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/onboarding03.imageset/onboarding03.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/onboarding03.imageset/onboarding03@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/onboarding03.imageset/onboarding03@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/onboarding04.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/onboarding04.imageset/onboarding04.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/onboarding04.imageset/onboarding04@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/onboarding04.imageset/onboarding04@3x.png
  NADA-iOS-forRelease/Resouces/Constants/Storyboard.swift
  NADA-iOS-forRelease/Resouces/Constants/ViewController.swift
  NADA-iOS-forRelease/Resouces/Constants/Xib.swift
  NADA-iOS-forRelease/Resouces/Storyboards/Onboarding/Onboarding.storyboard
  NADA-iOS-forRelease/Sources/Cells/Onboarding/OnboardingCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/Onboarding/OnboardingCollectionViewCell.xib
  NADA-iOS-forRelease/Sources/ViewControllers/Onboarding/OnboardingViewController.swift
Labels: Feat

#119 [FEAT] #117 - 명함생성 뷰 글자제한 구현
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.swift
Labels: Hyungyu 🐯, P1 / Priority High, Feat

#122 [FIX] #116 - 명함생성 뷰 옵션 정보 수정시에도 delegate 작동
  NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.swift
Labels: Hyungyu 🐯, Fix

#123 [FIX] #116 - Merge branch 'develop' into feature/#116
  NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCollectionViewCell.swift
Labels: Hyungyu 🐯, Fix

#127 [FEAT] #118 - FrontCardCell 에서 인스타 앱, 링크 사파리 연결
  NADA-iOS-forRelease/Info.plist
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
Labels: Hyungyu 🐯, P1 / Priority High, Feat

#129 [FEAT] #114 - 스플래시 뷰 구현, 탭바 수정 자잘한 작업 진행
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Constants/Storyboard.swift
  NADA-iOS-forRelease/Resouces/Constants/ViewController.swift
  NADA-iOS-forRelease/Resouces/Storyboards/Login/Login.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/Main/CardList.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/Splash/Splash.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/TabBar/TabBar.storyboard
  NADA-iOS-forRelease/Sources/NetworkService/User/UserAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserSevice.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Splash/SplashViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/TabBar/TabBarViewController.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Feat

#134 [FEAT] #101 - 카카오톡 소셜 로그인 서버 연결
  NADA-iOS-forRelease/Resouces/Constants/UserDefaults.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserSevice.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Feat

#137 [FEAT] #113 - 명함 상세 뷰 구현
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Constants/Storyboard.swift
  NADA-iOS-forRelease/Resouces/Constants/ViewController.swift
  NADA-iOS-forRelease/Resouces/Storyboards/CardDetail/CardDetail.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/CardDetail/CardHarmony.storyboard
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/MainCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/MainCardCell.xib
  NADA-iOS-forRelease/Sources/NetworkModel/Card/Card.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardResultBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CommonBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardHarmonyViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
Labels: Yijoon 🐨, Feat

#139 [FEAT] #131 - 궁합 뷰 구현
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHarmonyGreen.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHarmonyGreen.imageset/icnHarmonyGreen.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHarmonyGreen.imageset/icnHarmonyGreen@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHarmonyGreen.imageset/icnHarmonyGreen@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHarmonyOrange.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHarmonyOrange.imageset/icnHarmonyOrange.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHarmonyOrange.imageset/icnHarmonyOrange@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHarmonyOrange.imageset/icnHarmonyOrange@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHarmonyPurple.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHarmonyPurple.imageset/icnHarmonyPurple.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHarmonyPurple.imageset/icnHarmonyPurple@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHarmonyPurple.imageset/icnHarmonyPurple@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHarmonyRed.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHarmonyRed.imageset/icnHarmonyRed.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHarmonyRed.imageset/icnHarmonyRed@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHarmonyRed.imageset/icnHarmonyRed@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHarmonyYellow.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHarmonyYellow.imageset/icnHarmonyYellow.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHarmonyYellow.imageset/icnHarmonyYellow@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHarmonyYellow.imageset/icnHarmonyYellow@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/harmonyGreen.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/harmonyOrange.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/harmonyPurple.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/harmonyRed.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/harmonyYellow.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Extensions/UIColor+Extension.swift
  NADA-iOS-forRelease/Resouces/Storyboards/CardDetail/CardHarmony.storyboard
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardHarmonyViewController.swift
Labels: Yijoon 🐨, Feat

#138 [FIX] #133 - 메인에서 카드셀 좌우 스와이프로 바꾸기 구현
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Resouces/Constants/Xib.swift
  NADA-iOS-forRelease/Resouces/Storyboards/Main/Front.storyboard
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/MainCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/MainCardCell.xib
  NADA-iOS-forRelease/Sources/NetworkModel/Card/Card.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
Labels: Hyungyu 🐯, P1 / Priority High, Fix

#141 [FEAT] #135 - 더보기 뷰 셀 클릭 액션 작업 진행
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgChae.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgChae.imageset/imgChae.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgChae.imageset/imgChae@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgChae.imageset/imgChae@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgHyun.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgHyun.imageset/imgHyun.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgHyun.imageset/imgHyun@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgHyun.imageset/imgHyun@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgMin.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgMin.imageset/imgMin.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgMin.imageset/imgMin@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgMin.imageset/imgMin@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgYe.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgYe.imageset/imgYe.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgYe.imageset/imgYe@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgYe.imageset/imgYe@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgYi.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgYi.imageset/imgYi.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgYi.imageset/imgYi@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgYi.imageset/imgYi@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgYun.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgYun.imageset/imgYun.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgYun.imageset/imgYun@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgYun.imageset/imgYun@3x.png
  NADA-iOS-forRelease/Resouces/Constants/Storyboard.swift
  NADA-iOS-forRelease/Resouces/Constants/URL.swift
  NADA-iOS-forRelease/Resouces/Constants/ViewController.swift
  NADA-iOS-forRelease/Resouces/Constants/Xib.swift
  NADA-iOS-forRelease/Resouces/Storyboards/More/More.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/More/OpenSource.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/More/TeamNADA.storyboard
  NADA-iOS-forRelease/Sources/Cells/OpenSource/OpenSourceTableViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/OpenSource/OpenSourceTableViewCell.xib
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupService.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserSevice.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/OpenSource/OpenSourceViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/TeamNADA/TeamNADAViewController.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Feat

#143 [FEAT] #142 - 그룹명 변경 기능 구현
  .swiftlint.yml
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Constants/ViewController.swift
  NADA-iOS-forRelease/Sources/Cells/GroupEdit/GroupEditTableViewCell.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CommonBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/GroupNameEditBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardHarmonyViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/GroupEditViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Splash/SplashViewController.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Feat

#147 [CHORE] #146 - baseURL 수정
  NADA-iOS-forRelease/Resouces/Constants/URL.swift
Labels: Minjae 🐻‍❄️, 🚨review required🚨, Chore

#148 [FIX] #145 - 메인 flip 속도 조절 및 공유버튼 히든
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/MainCardCell.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/TeamNADA/TeamNADAViewController.swift
Labels: Hyungyu 🐯, Fix

#154 [FIX] #153 - 카드가 겹쳐보이는 버그
  NADA-iOS-forRelease/Sources/Cells/CardCell/MainCardCell.swift
Labels: Hyungyu 🐯, Fix

#150 [FIX] #144 - 카카오톡 소셜 로그인과 스플래시 뷰 연결, 수정
  NADA-iOS-forRelease/Resouces/Constants/UserDefaults.swift
  NADA-iOS-forRelease/Resouces/Storyboards/Splash/Splash.storyboard
  NADA-iOS-forRelease/Sources/AppDelegate.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardListLookUpRequest.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserSevice.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Splash/SplashViewController.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Fix

#155 [FIX] #152 - 뷰 수정 한번에 처리
  NADA-iOS-forRelease/Resouces/Storyboards/CardDetail/CardDetail.storyboard
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardResultBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/QRScanViewController.swift
Labels: Yijoon 🐨, Fix

#157 [FIX] #156 - 명함생성뷰 버그 해결
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.xib
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectBirthBottomViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectMBTIBottomViewController.swift
Labels: Hyungyu 🐯, P1 / Priority High, Fix

#159 [FIX] #158 - 명함생성뷰 이미지피커 dismiss 동작 추가
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift
Labels: Hyungyu 🐯, P1 / Priority High, Fix

#160 [FEAT] #151 - 메인 엠티 뷰, 로그인 뷰, 그룹 뷰 추가 작업
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/kakao_login_large_wide.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/kakao_login_large_wide.imageset/kakao_login_large_wide.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/kakao_login_large_wide.imageset/kakao_login_large_wide@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/kakao_login_large_wide.imageset/kakao_login_large_wide@3x.png
  NADA-iOS-forRelease/Resouces/Constants/Xib.swift
  NADA-iOS-forRelease/Resouces/Storyboards/Group/GroupEdit.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/Login/Login.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/Main/Front.storyboard
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/CardCell/EmptyCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/EmptyCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/CardCell/MainCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/GroupEdit/GroupEditTableViewCell.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/GroupNameEditBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/GroupEditViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Feat

#161 [CHORE] 세로모드 고정
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Info.plist
Labels: Chore

#163 [FIX] #162 - 명함생성 미리보기뷰, 명함상세뷰 flip 속도조절
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
Labels: Fix

#165 [FEAT] #164 - bearer token constant 화
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Constants/Header.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupService.swift
Labels: Yijoon 🐨, Feat

#172 [FIX] #171 - 명함생성 미리보기 뷰 안내문구 추가 및 서버 service 에 토큰 추가
  NADA-iOS-forRelease/Resouces/Storyboards/CardCreation/CardCreationPreview.storyboard
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardCreationRequest.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
Labels: Hyungyu 🐯, Fix, QA

#170 [FIX] #169 - 명함생성뷰 플레이스홀더 변경 및 상태바 위치 조절
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift
Labels: Hyungyu 🐯, Fix, QA

#175 [FIX] #174 - 알림창 문구 수정 (리스트, 로그아웃 뷰)
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
Labels: Minjae 🐻‍❄️, Fix, QA

#181 [FIX] #176 - 명함 앞면 뷰 URL 앞에 https:// 체크
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
Labels: Hyungyu 🐯, Fix, QA

#183 [FIX] #177 - 앞면 인스타그램 미입력 시 레이아웃 수정 및 뒷면 글머리 기호 추가
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/GroupCell/CardInGroupCollectionViewCell.xib
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
Labels: Hyungyu 🐯, Fix, QA

#179 [FEAT] 애플 소셜 로그인 구현
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/NADA-iOS-forRelease.entitlements
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/AppleLogin.imageset/AppleLogin-1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/AppleLogin.imageset/AppleLogin-1@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/AppleLogin.imageset/AppleLogin-1@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/AppleLogin.imageset/AppleLogin.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/AppleLogin.imageset/AppleLogin@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/AppleLogin.imageset/AppleLogin@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/AppleLogin.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconAdd.imageset/iconAdd-1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconAdd.imageset/iconAdd.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconAdd.imageset/iconAdd@2x-1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconAdd.imageset/iconAdd@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconAdd.imageset/iconAdd@3x-1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconAdd.imageset/iconAdd@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconList.imageset/iconList-1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconList.imageset/iconList.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconList.imageset/iconList@2x-1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconList.imageset/iconList@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconList.imageset/iconList@3x-1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconList.imageset/iconList@3x.png
  NADA-iOS-forRelease/Resouces/Constants/UserDefaults.swift
  NADA-iOS-forRelease/Resouces/Storyboards/Login/Login.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/Main/Front.storyboard
  NADA-iOS-forRelease/Sources/AppDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Feat

#186 [FEAT] #168 - 공유하기 뷰 구현
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/qrCodeImg21.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/qrCodeImg21.imageset/qrCodeImg21.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/qrCodeImg21.imageset/qrCodeImg21@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/qrCodeImg21.imageset/qrCodeImg21@3x.png
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Resouces/Extensions/UIViewController+Extension.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardShareBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/QRScanViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
Labels: Yijoon 🐨, Feat, Design

#185 [FEAT] #180 - 유저 관련 서버 추가 연결
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Sources/AppDelegate.swift
  NADA-iOS-forRelease/Sources/NetworkModel/User/UserTokenReissueRequset.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserSevice.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Splash/SplashViewController.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Feat

#191 [FEAT] #189 - Kingfisher 라이브러리 오픈소스 라이브러리에 추가
  NADA-iOS-forRelease/Resouces/Constants/URL.swift
  NADA-iOS-forRelease/Sources/ViewControllers/OpenSource/OpenSourceViewController.swift
Labels: Minjae 🐻‍❄️, Feat

#188 [FEAT] #140 - 명함 그룹 뷰 서버연결
  NADA-iOS-forRelease/Resouces/Storyboards/CardDetail/CardDetail.storyboard
  NADA-iOS-forRelease/Sources/Cells/CardCell/MainCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/GroupCell/CardInGroupCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/Card.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/TeamNADA/TeamNADAViewController.swift
Labels: Yijoon 🐨, Feat

#192 [FEAT] #187 - 명함 그룹 뷰 엠티 뷰 추가
  NADA-iOS-forRelease/Resouces/Storyboards/Group/Group.storyboard
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
Labels: Yijoon 🐨, Feat, Design

#194 [FEAT] #190 - 그룹 속 명함 삭제 서버
  NADA-iOS-forRelease/Resouces/Constants/Header.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
Labels: Yijoon 🐨, Feat

#196 [FEAT] #193 - cardCell 이미지 분기처리
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/MainCardCell.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
Labels: Yijoon 🐨, Feat

#197 [FIX] #195 - 명함생성 userId 추가 및 미리보기 행간 추가
  NADA-iOS-forRelease/Resouces/Storyboards/CardCreation/CardCreationPreview.storyboard
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardCreationRequest.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
Labels: Fix

#200 [FEAT] #199 - SceneDelegate에서 토큰 재발급 처리 로직 구현
  NADA-iOS-forRelease/Sources/NetworkService/User/UserAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserSevice.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Feat

#202 [FEAT] #201 - ID로 명함 검색해서 추가하기 서버
  NADA-iOS-forRelease/Resouces/Constants/UserDefaults.swift
  NADA-iOS-forRelease/Resouces/Extensions/UIViewController+Extension.swift
  NADA-iOS-forRelease/Sources/Cells/GroupCell/CardInGroupCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/GroupCell/CardInGroupCollectionViewCell.xib
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddWithIdBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardResultBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/Views/CardView.swift
  NADA-iOS-forRelease/Sources/Views/CardView.xib
Labels: Yijoon 🐨, Feat

#206 [FEAT] #198 - 첫 명함생성 시 바텀시트 구현
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/firsthandIcon.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/firsthandIcon.imageset/invalidName.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/firsthandIcon.imageset/invalidName@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/firsthandIcon.imageset/invalidName@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgFirstcard.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgFirstcard.imageset/imgFirstcard.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgFirstcard.imageset/imgFirstcard@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgFirstcard.imageset/imgFirstcard@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/secondhandIcon.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/secondhandIcon.imageset/invalidName.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/secondhandIcon.imageset/invalidName@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/secondhandIcon.imageset/invalidName@3x.png
  NADA-iOS-forRelease/Resouces/Constants/UserDefaults.swift
  NADA-iOS-forRelease/Resouces/Constants/ViewController.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/FirstCardAlertBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
Labels: Hyungyu 🐯, Fix

#205 [FIX] #204 - 키값으로 바꾸기
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardResultBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
Labels: Yijoon 🐨, Fix

#209 [FIX] #207 - 첫명함 알람 바텀시트 로직 변경
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
Labels: Fix

#213 [CHORE] #212 - 빌드 숫자 2로 올리기
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Info.plist
Labels: Yijoon 🐨, Chore

#215 [FEAT] #208 - 온보딩 과정 넣기
  NADA-iOS-forRelease/Resouces/Constants/UserDefaults.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
Labels: Hyungyu 🐯, P1 / Priority High, Fix

#217 [FEAT] #214 - initCell 에서 서버에서 받아오는 이미지 분기처리
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/MainCardCell.swift
Labels: Yijoon 🐨, Feat

#220 [FEAT] #219 - 명함 그룹 수정 서버
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
Labels: Feat

#222 [FEAT] #216 - 명함 이미지 렌더링해서 앨범에 저장 구현
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/MainCardCell.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardShareBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
Labels: Hyungyu 🐯, P1 / Priority High, Feat

#225 [FEAT] #184 - 리스트뷰, 메인 일부 서버 연결
  NADA-iOS-forRelease/Resouces/Extensions/UIViewController+Extension.swift
  NADA-iOS-forRelease/Sources/Cells/CardList/CardListTableViewCell.xib
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardListRequest.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserAPI.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Splash/SplashViewController.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Feat

#227 [FEAT] #226 - 메인 무한스크롤 구현 및 data 모델 정리
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/Card.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/MainListRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/CardsInGroupResponse.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/Groups.swift
  NADA-iOS-forRelease/Sources/NetworkModel/User/User.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddWithIdBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardShareBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/TeamNADA/TeamNADAViewController.swift
Labels: Hyungyu 🐯, P1 / Priority High, Feat

#228 [FEAT] #223 - QR 생성, QR스캔 서버
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Constants/Status.swift
  NADA-iOS-forRelease/Resouces/Extensions/String+Extension.swift
  NADA-iOS-forRelease/Sources/Classes/QRCodeView.swift
  NADA-iOS-forRelease/Sources/Classes/TempClass.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/Card.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/CardsInGroupResponse.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardAPI.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddWithIdBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardResultBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardShareBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/QRScanViewController.swift
Labels: Yijoon 🐨, Feat

#229 [FEAT] #224 - 그룹 편집 뷰 서버 연결
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Constants/UserDefaults.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardListLookUp.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardListLookUpRequest.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardAPI.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/GroupNameEditBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/GroupEditViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Feat

#231 [FEAT] #221 - 명함 궁합 서버
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Sources/NetworkModel/Util/HarmonyResponse.swift
  NADA-iOS-forRelease/Sources/NetworkService/Util/UtilAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Util/UtilService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardHarmonyViewController.swift
Labels: Yijoon 🐨, Feat

#232 [REFACTOR] #230 - 명함생성뷰 userID 로직 설정
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
Labels: Hyungyu 🐯, Refactor

#234 [FEAT] #233 - UserDefault 토큰으로 헤더 변경
  NADA-iOS-forRelease/Resouces/Constants/Header.swift
  NADA-iOS-forRelease/Resouces/Constants/UserDefaults.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddWithIdBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardResultBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/QRScanViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/GroupEditViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
Labels: Yijoon 🐨, Feat

#238 [FEAT] #237 - 갤러리 권한 설정 문구
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardShareBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/Views/CardView.xib
Labels: Yijoon 🐨, Feat

#239 [FIX] #235 - 명함생성 userID 가져오기 및 메인 카드 리스트 조회 로직 변경
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
Labels: Hyungyu 🐯, P1 / Priority High, Fix

#243 [CHORE] #242 - release1.0/1 -> develop 머지하기
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Info.plist
  NADA-iOS-forRelease/Resouces/Constants/Header.swift
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Resouces/Constants/Status.swift
  NADA-iOS-forRelease/Resouces/Constants/UserDefaults.swift
  NADA-iOS-forRelease/Resouces/Extensions/String+Extension.swift
  NADA-iOS-forRelease/Resouces/Extensions/UIViewController+Extension.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/MainCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardList/CardListTableViewCell.xib
  NADA-iOS-forRelease/Sources/Classes/QRCodeView.swift
  NADA-iOS-forRelease/Sources/Classes/TempClass.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/Card.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardListLookUp.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardListLookUpRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardListRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/MainListRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/CardsInGroupResponse.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/Groups.swift
  NADA-iOS-forRelease/Sources/NetworkModel/User/User.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Util/HarmonyResponse.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Util/UtilAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Util/UtilService.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddWithIdBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardResultBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardShareBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/GroupNameEditBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardHarmonyViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/QRScanViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/GroupEditViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Splash/SplashViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/TeamNADA/TeamNADAViewController.swift
  NADA-iOS-forRelease/Sources/Views/CardView.xib
Labels: Minjae 🐻‍❄️, Yijoon 🐨, Hyungyu 🐯, Chore

#245 [CHORE] #244 - 빌드 3으로 업데이트
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
Labels: Yijoon 🐨, Chore

#248 [FIX] #247 - 메인뷰 명함리스트조회 로직 변경 및 명함생성 url 포함시키기
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
Labels: Hyungyu 🐯, Fix, QA

#250 [FIX] #249 - 재설치 시 메인 명함리스트 비워지는 이슈
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
Labels: Hyungyu 🐯, Fix, QA

#256 [FIX] #255 - 명함생성 후 두번째 명함으로 이동 및 리스트편집 후 첫번째 명함으로 이동
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
Labels: Hyungyu 🐯, P1 / Priority High, Fix

#254 [FIX] #253 - 카카오톡 로그인 post 서버 통신 시, oauthToken을 사용하도록 변경
  NADA-iOS-forRelease/Resouces/Constants/Const.swift
  NADA-iOS-forRelease/Resouces/Constants/Header.swift
  NADA-iOS-forRelease/Resouces/Constants/UserDefaults.swift
  NADA-iOS-forRelease/Sources/AppDelegate.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupService.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserSevice.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Splash/SplashViewController.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Fix

#261 [FEAT] #257 - 명함 그룹뷰 인파이나이트스크롤 구현
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Sources/Cells/GroupCell/CardInGroupCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/QRScanViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/GroupEditViewController.swift
Labels: Hyungyu 🐯, Feat

#263 [FIX] #262 - 명함 모음 리로드 로직 수정
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/QRScanViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/GroupEditViewController.swift
Labels: Hyungyu 🐯, P1 / Priority High, Fix

#264 [FEAT] #218 - 명함 그룹 뷰 1차 버그 해결
  NADA-iOS-forRelease/Info.plist
  NADA-iOS-forRelease/Resouces/Storyboards/CardDetail/CardDetail.storyboard
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddWithIdBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
Labels: Yijoon 🐨, Feat

#266 [FIX] #260 - 그룹 편집 리로드 버그 해결
  NADA-iOS-forRelease/Resouces/Constants/Header.swift
  NADA-iOS-forRelease/Resouces/Extensions/UIColor+Extension.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CommonBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/GroupNameEditBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/GroupEditViewController.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Fix

#270 [FEAT] #269 - QR 스캔 재시작 구현
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardResultBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CommonBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/QRScanViewController.swift
Labels: Hyungyu 🐯, Feat

#268 [FEAT] #267 - 리스트, 그룹 편집 엠티뷰 추가
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Constants/Xib.swift
  NADA-iOS-forRelease/Resouces/Storyboards/Group/Group.storyboard
  NADA-iOS-forRelease/Sources/Cells/CardList/EmptyCardListTableViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardList/EmptyCardListTableViewCell.xib
  NADA-iOS-forRelease/Sources/Cells/GroupEdit/EmptyGroupEditTableViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/GroupEdit/EmptyGroupEditTableViewCell.xib
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/GroupEditViewController.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Feat

#271 [FEAT] #265 - 동일한 그룹명 alert
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddGroupBottomSheetViewController.swift
Labels: Yijoon 🐨, Feat

#273 [CHORE] #272 - release1.0/3 -> develop 머지하기
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Info.plist
  NADA-iOS-forRelease/Resouces/Constants/Const.swift
  NADA-iOS-forRelease/Resouces/Constants/Header.swift
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Resouces/Constants/UserDefaults.swift
  NADA-iOS-forRelease/Resouces/Constants/Xib.swift
  NADA-iOS-forRelease/Resouces/Extensions/UIColor+Extension.swift
  NADA-iOS-forRelease/Resouces/Storyboards/CardDetail/CardDetail.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/Group/Group.storyboard
  NADA-iOS-forRelease/Sources/AppDelegate.swift
  NADA-iOS-forRelease/Sources/Cells/CardList/EmptyCardListTableViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardList/EmptyCardListTableViewCell.xib
  NADA-iOS-forRelease/Sources/Cells/GroupCell/CardInGroupCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/GroupEdit/EmptyGroupEditTableViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/GroupEdit/EmptyGroupEditTableViewCell.xib
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupService.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserSevice.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddWithIdBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardResultBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CommonBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/GroupNameEditBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/QRScanViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/GroupEditViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Splash/SplashViewController.swift
Labels: Minjae 🐻‍❄️, Yijoon 🐨, Hyungyu 🐯, Chore

#276 [FIX] #275 - 빌드4로 변경 및 명함생성 시 TMI 들어가지 않는 로직 수정
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardCreationRequest.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift
Labels: Hyungyu 🐯, Fix

#279 [FIX] #278 - 바텀시트 뒷배경 불투명도 수정
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CommonBottomSheetViewController.swift
Labels: Hyungyu 🐯, Fix

#281 [FEAT] #280 - 명함생성 시 activity indicator 추가
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
  Podfile
  Podfile.lock
Labels: Hyungyu 🐯, P2 / Priority Middle, Feat

#285 [FIX] #284 - 카카오톡 로그인 post 서버, oauthToken에서 email값으로 변경
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Fix
