Repository TeamNADA/NADA-iOS-ForRelease, pull requests merged in 2021-10, with the labels that each got.

#16 [#14] - 명함 리스트 뷰 구현
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/arrowBackIosNewWhite.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/arrowBackIosNewWhite.imageset/arrowBackIosNewWhite24Dp1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/arrowBackIosNewWhite.imageset/arrowBackIosNewWhite24Dp1@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/arrowBackIosNewWhite.imageset/arrowBackIosNewWhite24Dp1@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/pushPinBlack.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/pushPinBlack.imageset/pushPinBlack24Dp1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/pushPinBlack.imageset/pushPinBlack24Dp1@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/pushPinBlack.imageset/pushPinBlack24Dp1@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/pushPinBlackFilled.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/pushPinBlackFilled.imageset/pushPinBlack24Dp1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/pushPinBlackFilled.imageset/pushPinBlack24Dp1@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/pushPinBlackFilled.imageset/pushPinBlack24Dp1@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/reorderBlack.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/reorderBlack.imageset/reorderBlack24Dp1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/reorderBlack.imageset/reorderBlack24Dp1@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/reorderBlack.imageset/reorderBlack24Dp1@3x.png
  NADA-iOS-forRelease/Resouces/Constants/Storyboard.swift
  NADA-iOS-forRelease/Resouces/Constants/ViewController.swift
  NADA-iOS-forRelease/Resouces/Extensions/UIView+Extension.swift
  NADA-iOS-forRelease/Resouces/Storyboards/CardList.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/Login.storyboard
  NADA-iOS-forRelease/Sources/Cells/CardList/CardListTableViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardList/CardListTableViewCell.xib
  NADA-iOS-forRelease/Sources/Models/CardList/CardListDataModel.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Feat

#19 [#17] - 컬러 에셋 추가
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/black.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/delete.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/errorBackground.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/errorText.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/group1.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/group2.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/group3.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/group4.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/hint.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/inputBlack.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/listSelectedBlack.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/mainBlue.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/matchButton.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/modalBackground.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/modalButton.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/step.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/unselectedOption.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/white.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Constants/Color.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Chore

#21 [#20] - 명함 리스트뷰 Alert창 구현 & 연결
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Extensions/UIAlertController+Extension.swift
  NADA-iOS-forRelease/Resouces/Extensions/UIViewController+Extension.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Feat

#23 [#22] initializer 메서드 컨밴션에 맞춰 네이밍 변경 및 cell 리펙토링
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Constants/Xib.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardList/CardListTableViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCollectionViewCell.xib
  NADA-iOS-forRelease/Sources/Cells/CreationCard/Background/BackgroundCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/Background/BackgroundCollectionViewCell.xib
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.xib
  NADA-iOS-forRelease/Sources/Cells/CreationCard/RequiredFlavor/RequiredFlavorCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/RequiredFlavor/RequiredFlavorCollectionViewCell.xib
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
Labels: Hyungyu 🐯, Refactor

#25 [#24] 명함 메인화면 구현
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease.xcodeproj/xcshareddata/xcschemes/NADA-iOS-forRelease.xcscheme
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/instagramWhite.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/instagramWhite.imageset/instagramWhite.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/instagramWhite.imageset/instagramWhite@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/instagramWhite.imageset/instagramWhite@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/testBg.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/testBg.imageset/bg1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/testBg.imageset/bg1@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/testBg.imageset/bg1@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/testLink.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/testLink.imageset/linkBlack24Dp1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/testLink.imageset/linkBlack24Dp1@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/testLink.imageset/linkBlack24Dp1@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/black.colorset/Contents 2.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/delete.colorset/Contents 2.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/errorBackground.colorset/Contents 2.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/errorText.colorset/Contents 2.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/group1.colorset/Contents 2.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/group2.colorset/Contents 2.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/group3.colorset/Contents 2.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/group4.colorset/Contents 2.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/hint.colorset/Contents 2.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/inputBlack.colorset/Contents 2.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/listSelectedBlack.colorset/Contents 2.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/mainBlue.colorset/Contents 2.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/matchButton.colorset/Contents 2.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/modalBackground.colorset/Contents 2.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/modalButton.colorset/Contents 2.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/step.colorset/Contents 2.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/unselectedOption.colorset/Contents 2.json
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/white.colorset/Contents 2.json
  NADA-iOS-forRelease/Resouces/Constants/Storyboard.swift
  NADA-iOS-forRelease/Resouces/Constants/ViewController.swift
  NADA-iOS-forRelease/Resouces/Storyboards/Base.lproj/Main.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/Main/Front.storyboard
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/CardList/CardListTableViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/Background/BackgroundCollectionViewCell 2.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/RequiredFlavor/RequiredFlavorCollectionViewCell 2.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Feat

#27 [FEAT] #18 - 명함생성 뷰 텍스트필드 기능 구현
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Resouces/Constants/Storyboard.swift
  NADA-iOS-forRelease/Resouces/Constants/ViewController.swift
  NADA-iOS-forRelease/Resouces/Extensions/TempExtensions.swift
  NADA-iOS-forRelease/Resouces/Storyboards/Base.lproj/Main.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/CardCreation/CardCreation.storyboard
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/RequiredFlavor/RequiredFlavorCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/MainViewController.swift
Labels: Hyungyu 🐯, Feat

#38 [REFACTOR] #37 - Color Extension 적용
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Extensions/UIFont+Extension.swift
  NADA-iOS-forRelease/Resouces/Extensions/UIViewController+Extension.swift
  NADA-iOS-forRelease/Resouces/Fonts/TempFont.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/RequiredFlavor/RequiredFlavorCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift
Labels: Hyungyu 🐯, Refactor

#45 [DESIGN] #44 - 메인 화면 Card Flip 기능 구현
  .swiftlint.yml
  NADA-iOS-forRelease/Resouces/Storyboards/CardList.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/Main/Front.storyboard
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.xib
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CustomTabBar/CustomTabBarController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
  NADA-iOS-forRelease/Sources/Views/StackItemView.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Feat

#48 [FEAT] #47 - 리스트뷰 세부 기능 수정과 추가
  .swiftlint.yml
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Resouces/Storyboards/CardList.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/CustomTabBar.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/Main/Front.storyboard
  NADA-iOS-forRelease/Sources/Cells/CardList/CardListTableViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardList/CardListTableViewCell.xib
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CustomTabBar/CustomTabBarController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
Labels: Minjae 🐻‍❄️, P2 / Priority Middle, Feat
