Repository TeamNADA/NADA-iOS-ForRelease, pull requests merged in 2021-09, with the labels that each got.

#7 [#6] VerticalCardSwiper pod install
  Podfile
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/Target Support Files/Pods-NADA-iOS-forRelease/Pods-NADA-iOS-forRelease-acknowledgements.markdown
  Pods/Target Support Files/Pods-NADA-iOS-forRelease/Pods-NADA-iOS-forRelease-acknowledgements.plist
  Pods/Target Support Files/Pods-NADA-iOS-forRelease/Pods-NADA-iOS-forRelease-frameworks-Debug-input-files.xcfilelist
  Pods/Target Support Files/Pods-NADA-iOS-forRelease/Pods-NADA-iOS-forRelease-frameworks-Debug-output-files.xcfilelist
  Pods/Target Support Files/Pods-NADA-iOS-forRelease/Pods-NADA-iOS-forRelease-frameworks-Release-input-files.xcfilelist
  Pods/Target Support Files/Pods-NADA-iOS-forRelease/Pods-NADA-iOS-forRelease-frameworks-Release-output-files.xcfilelist
  Pods/Target Support Files/Pods-NADA-iOS-forRelease/Pods-NADA-iOS-forRelease-frameworks.sh
  Pods/Target Support Files/Pods-NADA-iOS-forRelease/Pods-NADA-iOS-forRelease.debug.xcconfig
  Pods/Target Support Files/Pods-NADA-iOS-forRelease/Pods-NADA-iOS-forRelease.release.xcconfig
  Pods/Target Support Files/VerticalCardSwiper/VerticalCardSwiper-Info.plist
  Pods/Target Support Files/VerticalCardSwiper/VerticalCardSwiper-dummy.m
  Pods/Target Support Files/VerticalCardSwiper/VerticalCardSwiper-prefix.pch
  Pods/Target Support Files/VerticalCardSwiper/VerticalCardSwiper-umbrella.h
  Pods/Target Support Files/VerticalCardSwiper/VerticalCardSwiper.debug.xcconfig
  Pods/Target Support Files/VerticalCardSwiper/VerticalCardSwiper.modulemap
  Pods/Target Support Files/VerticalCardSwiper/VerticalCardSwiper.release.xcconfig
  Pods/VerticalCardSwiper/LICENSE
  Pods/VerticalCardSwiper/README.md
  Pods/VerticalCardSwiper/Sources/CardCell.swift
  Pods/VerticalCardSwiper/Sources/CardDelegate.swift
  Pods/VerticalCardSwiper/Sources/Extensions.swift
  Pods/VerticalCardSwiper/Sources/PanDirection.swift
  Pods/VerticalCardSwiper/Sources/SwipeDirection.swift
  Pods/VerticalCardSwiper/Sources/VerticalCardSwiper.swift
  Pods/VerticalCardSwiper/Sources/VerticalCardSwiperDatasource.swift
  Pods/VerticalCardSwiper/Sources/VerticalCardSwiperDelegate.swift
  Pods/VerticalCardSwiper/Sources/VerticalCardSwiperFlowLayout.swift
  Pods/VerticalCardSwiper/Sources/VerticalCardSwiperView.swift
Labels: Hyungyu 🐯, Add

#8 [#5] 명함 앞면 구현
  .swiftlint.yml
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/TempCell.swift
Labels: Design

#13 [#12] - 로그인 뷰 디자인 변경
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/Mask Group.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/Mask Group.imageset/Mask Group.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/Mask Group.imageset/Mask Group@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/Mask Group.imageset/Mask Group@3x.png
  NADA-iOS-forRelease/Resouces/Storyboards/Login.storyboard
Labels: Minjae 🐻‍❄️, Design

#15 [FEAT]명함 생성 뷰(작성) 구현
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/addPhotoAlternateBlack24Dp1.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/addPhotoAlternateBlack24Dp1.imageset/addPhotoAlternateBlack24Dp1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/addPhotoAlternateBlack24Dp1.imageset/addPhotoAlternateBlack24Dp1@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/addPhotoAlternateBlack24Dp1.imageset/addPhotoAlternateBlack24Dp1@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/closeBlack24Dp.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/closeBlack24Dp.imageset/closeBlack24Dp.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/closeBlack24Dp.imageset/closeBlack24Dp@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/closeBlack24Dp.imageset/closeBlack24Dp@3x.png
  NADA-iOS-forRelease/Resouces/Constants/Storyboard.swift
  NADA-iOS-forRelease/Resouces/Constants/ViewController.swift
  NADA-iOS-forRelease/Resouces/Storyboards/CardCreation/CardCreation.storyboard
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCell.xib
  NADA-iOS-forRelease/Sources/Cells/CreationCard/CardBackgroundSetting/CardBackgroundSettingCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/CardBackgroundSetting/CardBackgroundSettingCell.xib
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCell.xib
  NADA-iOS-forRelease/Sources/Cells/CreationCard/RequiredFlavor/RequiredFlavorCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/RequiredFlavor/RequiredFlavorCell.xib
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift
  Pods/Pods.xcodeproj/project.pbxproj
Labels: Hyungyu 🐯, Feat
