Repository TeamNADA/NADA-iOS-ForRelease, pull requests merged in 2022-01, with the labels that each got.

#288 [FEAT] #287 - NVActivityIndicatorView 오픈소스 라이브러리 추가
  NADA-iOS-forRelease/Resouces/Constants/URL.swift
  NADA-iOS-forRelease/Sources/ViewControllers/OpenSource/OpenSourceViewController.swift
Labels: Minjae 🐻‍❄️, Feat

#290 [CHORE] #289 - 빌드 숫자 5로 업데이트
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
Labels: Yijoon 🐨, Chore

#293 [CHORE] #292 - release1.0/4-> develop 머지하기
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Constants/URL.swift
  NADA-iOS-forRelease/Sources/Cells/GroupCell/CardInGroupCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardCreationRequest.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CommonBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/GroupEditViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/OpenSource/OpenSourceViewController.swift
  Podfile
  Podfile.lock
Labels: Minjae 🐻‍❄️, Yijoon 🐨, Hyungyu 🐯, Chore

#295 [CHORE] #291 - 로그인 버튼 레이아웃 조정
  NADA-iOS-forRelease/Resouces/Storyboards/Login/Login.storyboard
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Chore

#297 [CHORE] #294 - 앱 언어 한국어로 변경하기
  NADA-iOS-forRelease/Info.plist
Labels: Yijoon 🐨, Chore

#299 [FEAT] 온보딩 스플래시 뷰에 연결
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectBirthBottomViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Splash/SplashViewController.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Feat

#300 [FIX] #298 -그룹명 dynamic Cell 코드 수정
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
Labels: Yijoon 🐨, Fix

#302 [FIX] #301 - 그룹 편집 뷰 그룹명 길이 제한
  NADA-iOS-forRelease/Sources/Cells/GroupEdit/GroupEditTableViewCell.xib
Labels: Minjae 🐻‍❄️, P2 / Priority Middle, Fix

#303 [FIX] #286 - 무한스크롤 오프셋 개선 및 로딩창 수정
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Resouces/Extensions/UIColor+Extension.swift
  NADA-iOS-forRelease/Resouces/Storyboards/CardCreation/CardCreation.storyboard
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
Labels: Hyungyu 🐯, P1 / Priority High, Fix

#305 [CHORE] #304 - 카카오 로그인 버튼 수정
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/btn_kakaologin.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/btn_kakaologin.imageset/btn_kakaologin.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/btn_kakaologin.imageset/btn_kakaologin@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/btn_kakaologin.imageset/btn_kakaologin@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/kakao_login_large_wide.imageset/kakao_login_large_wide.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/kakao_login_large_wide.imageset/kakao_login_large_wide@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/kakao_login_large_wide.imageset/kakao_login_large_wide@3x.png
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
Labels: Minjae 🐻‍❄️, P1 / Priority High, Chore

#306 [CHORE] release1.0/6 -> develop 머지하기
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Info.plist
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/btn_kakaologin.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/btn_kakaologin.imageset/btn_kakaologin.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/btn_kakaologin.imageset/btn_kakaologin@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/btn_kakaologin.imageset/btn_kakaologin@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/kakao_login_large_wide.imageset/kakao_login_large_wide.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/kakao_login_large_wide.imageset/kakao_login_large_wide@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/kakao_login_large_wide.imageset/kakao_login_large_wide@3x.png
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Resouces/Extensions/UIColor+Extension.swift
  NADA-iOS-forRelease/Resouces/Storyboards/CardCreation/CardCreation.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/Login/Login.storyboard
  NADA-iOS-forRelease/Sources/Cells/GroupEdit/GroupEditTableViewCell.xib
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectBirthBottomViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Splash/SplashViewController.swift
Labels: Chore

#308 [CHORE] release1.0.1/1 -> develop 머지하기
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Info.plist
Labels: Yijoon 🐨, Chore

#312 [FIX] 토큰 정보 UserDefaults에서 KeyChain으로 저장 방법 변경
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Constants/Const.swift
  NADA-iOS-forRelease/Resouces/Constants/KeyChainKey.swift
  NADA-iOS-forRelease/Resouces/Constants/UserDefaults.swift
  NADA-iOS-forRelease/Sources/AppDelegate.swift
  NADA-iOS-forRelease/Sources/AppModel/CardList/CardListDataModel.swift
  NADA-iOS-forRelease/Sources/NetworkModel/KeyChain.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
Labels: Minjae 🐻‍❄️, P2 / Priority Middle, Fix, Del
