Repository TeamNADA/NADA-iOS-ForRelease, pull requests merged in 2023-11, with the labels that each got.

#654 fix: 잠금화면 위젯 오류 해결 (#632)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Info.plist
  Widgets/Resource/Assets.xcassets/icnArrowForward.imageset/Contents.json
  Widgets/Resource/Assets.xcassets/icnArrowForward.imageset/icnArrowForward.png
  Widgets/Resource/Assets.xcassets/icnArrowForward.imageset/icnArrowForward@2x.png
  Widgets/Resource/Assets.xcassets/icnArrowForward.imageset/icnArrowForward@3x.png
  Widgets/Resource/Assets.xcassets/icnArrowForward.imageset/iconArrowRight.png
  Widgets/Resource/Assets.xcassets/icnArrowForward.imageset/iconArrowRight@2x.png
  Widgets/Resource/Assets.xcassets/icnArrowForward.imageset/iconArrowRight@3x.png
  Widgets/Resource/Assets.xcassets/imgCardBg01.imageset/Contents.json
  Widgets/Resource/Assets.xcassets/imgCardBg01.imageset/imgCardBg01.png
  Widgets/Resource/Assets.xcassets/imgCardBg01.imageset/imgCardBg01@2x.png
  Widgets/Resource/Assets.xcassets/imgCardBg01.imageset/imgCardBg01@3x.png
  Widgets/Resource/Extension/Color+Extension.swift
  Widgets/Resource/Extension/Font+Extension.swift
  Widgets/WidgetsBundle/MyCardWidget.swift
  Widgets/WidgetsBundle/OpenAppLockScreenWidget.swift
  Widgets/WidgetsBundle/QRCodeWidget.swift
Labels: Hyungyu 🐯, Fix, QA

#656 feat: 명함 생성 뷰내에서는 입력하던 태그 저장 (#655)
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Tag/SendTagSheetVC.swift
Labels: Hyungyu 🐯, Feat, QA

#653 feat: 명함 뒷면 블러 뷰 추가 (#652)
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.xib
Labels: Hyungyu 🐯, Feat

#657 fix: IQKeyboardManagerSwift (6.5.16) 업데이트 후 UI 버그 (#637)
  NADA-iOS-forRelease/Sources/ViewControllers/Tag/SendTagSheetVC.swift
  Podfile.lock
Labels: Hyungyu 🐯, Fix, QA

#659 bug: 일부 경우 명함을 돌렸을 때 여전히 앞면인 경우 해결 (#658)
  NADA-iOS-forRelease/Sources/Cells/CardCell/MainCardCell.swift
Labels: Hyungyu 🐯, bug

#662 design: alpha 값 변경 (#661)
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.xib
Labels: Hyungyu 🐯, Design

#666 chore: 엠티뷰 이미지 에셋 변경 (#665)
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgSendTagEmpty.imageset/imgSendTagEmpty 1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgSendTagEmpty.imageset/imgSendTagEmpty@2x 1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgSendTagEmpty.imageset/imgSendTagEmpty@3x 1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgTagEmptyView.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgTagEmptyView.imageset/imgTagEmptyView 1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgTagEmptyView.imageset/imgTagEmptyView.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgTagEmptyView.imageset/imgTagEmptyView@2x 1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgTagEmptyView.imageset/imgTagEmptyView@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgTagEmptyView.imageset/imgTagEmptyView@3x 1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgTagEmptyView.imageset/imgTagEmptyView@3x.png
  NADA-iOS-forRelease/Sources/ViewControllers/Tag/FetchTagSheetVC.swift
Labels: Hyungyu 🐯, Chore

#668 feat: 명함 뒷면 밸런스 게임 하트 추가 (#667)
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgHeartSmall.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgHeartSmall.imageset/imgHeartSmall.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgHeartSmall.imageset/imgHeartSmall@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgHeartSmall.imageset/imgHeartSmall@3x.png
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.xib
Labels: Hyungyu 🐯, Feat, QA

#670 fix: 태그 보내기 뷰 툴바 삭제, IQKeyboardManger 재활성화하기 (#669)
  NADA-iOS-forRelease/Sources/ViewControllers/Tag/SendTagSheetVC.swift
Labels: Hyungyu 🐯, Fix, QA

#672 feat: 명함 상세 풀 투 리프레시 기능 (#671)
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
Labels: Yijoon 🐨, Feat

#674 fix: 스크롤 뷰 dynamic height 고치기 (#673)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Storyboards/CardDetail/CardDetail.storyboard
  NADA-iOS-forRelease/Resouces/Utils/safeAreaInset.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
Labels: Yijoon 🐨, Fix
