Repository TeamNADA/NADA-iOS-ForRelease, pull requests merged in 2023-04, with the labels that each got.

#378 feat: 근처의 명함 뷰 UI #374
  .swiftlint.yml
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnPlusCircle.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnPlusCircle.imageset/icnPlusCircle.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnPlusCircle.imageset/icnPlusCircle@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnPlusCircle.imageset/icnPlusCircle@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconRefreshLocation.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconRefreshLocation.imageset/iconRefreshLocation.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconRefreshLocation.imageset/iconRefreshLocation@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconRefreshLocation.imageset/iconRefreshLocation@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgProfileSmall.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgProfileSmall.imageset/imgProfileSmall.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgProfileSmall.imageset/imgProfileSmall@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgProfileSmall.imageset/imgProfileSmall@3x.png
  NADA-iOS-forRelease/Resouces/Constants/Storyboard.swift
  NADA-iOS-forRelease/Resouces/Extensions/UIStackView+Extension.swift
  NADA-iOS-forRelease/Resouces/Utils/getClassName.swift
  NADA-iOS-forRelease/Resouces/Utils/makeVibrate.swift
  NADA-iOS-forRelease/Sources/Factory/ModuleFactory.swift
  NADA-iOS-forRelease/Sources/Factory/controllerFromStoryBoard.swift
  NADA-iOS-forRelease/Sources/NetworkModel/AroundMe/AroundMeResponse.swift
  NADA-iOS-forRelease/Sources/Protocols/ViewModelType.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/AroundMe/VC/AroundMeViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/AroundMe/View/AroundMeCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/ViewControllers/AroundMe/ViewModel/AroundMeViewModel.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Home/VC/HomeViewController.swift
  NADA-iOS-forRelease/Sources/Views/CardView/CardView.swift
  NADA-iOS-forRelease/Sources/Views/CardView/CardView.xib
  NADA-iOS-forRelease/Sources/Views/CustomNavigationBar/CustomNavigationBar.swift
  Podfile
  Podfile.lock
Labels: Yijoon 🐨, Feat

#404 fix: 명함 아이디 검색 API 수정 (#401)
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddWithIdBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/QRScanViewController.swift
Labels: Hyungyu 🐯, Fix

#406 fix: 명함 순서 변경 시 CardReorderInfo 수정 (#402)
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardReorderInfo.swift
Labels: Hyungyu 🐯, Fix

#409 feat: 업데이트 팝업 뷰 서버통신 통해 비강제, 강제 업데이트를 구현 (#397)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Sources/Factory/ModuleFactory.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Update/UpdateNote.swift
  NADA-iOS-forRelease/Sources/NetworkService/Update/UpdateService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Home/VC/HomeViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Update/VC/UpdateViewController.swift
  Podfile.lock
Labels: Hyungyu 🐯, Feat

#414 fix: 카드 리스트 뷰에서 조회 및 재정렬할 때 사용하는 데이터모델 자료형 수정 (#413)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardListRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/CardListInGroupRequest.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
Labels: Hyungyu 🐯, Fix

#416 fix: 취향 조회 path 와 데이터 모델 Taste 수정 (#415)
  NADA-iOS-forRelease/Sources/NetworkModel/Card/Taste.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/VC/CardCreationViewController.swift
Labels: Hyungyu 🐯, Fix

#420 feat: 명함 생성 뒷면 기능 확인 (#396)
  NADA-iOS-forRelease/Resouces/Storyboards/CardCreation/CardCreationPreview.storyboard
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardCreationRequest.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/VC/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/VC/CardCreationViewController.swift
Labels: Hyungyu 🐯, Feat

#421 fix: 명함 생성 API 기능 구현 확인 (#419)
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/Card.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardCreationRequest.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardResultBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/VC/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/TeamNADA/TeamNADAViewController.swift
Labels: Hyungyu 🐯, Fix

#426 feat: 위치 정보 테스트 #423
  NADA-iOS-forRelease/Info.plist
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardShareBottomSheetViewController.swift
Labels: Yijoon 🐨, Feat

#428 fix: 명함 리스트 순서 변경 기능 확인
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardReorderInfo.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
Labels: Hyungyu 🐯, Fix

#431 feat: 명함 생성 시 내 명함 탭으로 이동 (#424)
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/VC/CardCreationPreviewViewController.swift
Labels: Hyungyu 🐯, Feat

#432 feat: 명함 그룹 조회 API 연결 #422
  NADA-iOS-forRelease/Sources/Cells/GroupCell/CardInGroupCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/CardListInGroupRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/CardsInGroupResponse.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/Groups.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/GroupNameEditBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/GroupEditViewController.swift
Labels: Yijoon 🐨, Feat

#435 fix: 명함 앞면 선택사항 없을 시 아이콘 없애기 (#429)
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
Labels: Hyungyu 🐯, Fix

#436 design: 업데이트 뷰 체크박스와 라벨의 정렬 수정 (#407)
  NADA-iOS-forRelease/Sources/ViewControllers/Update/VC/UpdateViewController.swift
Labels: Hyungyu 🐯, Design

#440 fix: 카드 삭제 API 수정 (#439)
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardAPI.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
Labels: Hyungyu 🐯, Fix

#441 feat: 명함 생성 전화번호 텍스트필드 기능 구현 (#417)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.swift
  Podfile.lock
Labels: Hyungyu 🐯, Feat

#443 fix: 명함 그룹에 명함 연결 (#442, #342)
  NADA-iOS-forRelease/Resouces/Constants/UserDefaults.swift
  NADA-iOS-forRelease/Sources/AppDelegate.swift
  NADA-iOS-forRelease/Sources/Factory/ModuleFactory.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/CardAddInGroupRequest.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupService.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardShareBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/QRScanViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Home/VC/HomeViewController.swift
  NADA-iOS-forRelease/Sources/Views/CardView/CardView.xib
Labels: Hyungyu 🐯, Fix

#446 fix: 명함 뒷면 다크모드 대응 (#444)
  NADA-iOS-forRelease/Resouces/Extensions/UIColor+Extension.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.xib
Labels: Hyungyu 🐯, Fix

#452 fix: 명함 생성 생일 양식 변경 (#448)
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectBirthBottomViewController.swift
Labels: Hyungyu 🐯, Fix

#453 fix: 사용자 업데이트 정보 조회 데이터 모델 수정 (#451)
  NADA-iOS-forRelease/Sources/NetworkModel/Update/UpdateUserInfo.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Home/VC/HomeViewController.swift
Labels: Hyungyu 🐯, Fix

#445 feat: 명함 선택 시 사진 영역 수정 (#333)
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/VC/CardCreationViewController.swift
  Podfile
  Podfile.lock
Labels: Hyungyu 🐯, Feat

#455 feat: 확인했어요 API 구현 (#454)
  NADA-iOS-forRelease/Sources/NetworkService/Update/UpdateAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Update/UpdateService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Home/VC/HomeViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Update/VC/UpdateViewController.swift
Labels: Hyungyu 🐯, Feat

#461 feat: 마이페이지 회원탈퇴, 받은 명함 초기화 구현 (#460)
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupService.swift
  NADA-iOS-forRelease/Sources/NetworkService/Plugin/MoyaLoggerPlugin.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserSevice.swift
  NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
Labels: Hyungyu 🐯, Feat
