Repository TeamNADA/NADA-iOS-ForRelease, pull requests merged in 2023-10, with the labels that each got.

#605 feat: 메인화면 배너 서버 (#604)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Sources/NetworkModel/Update/BannerResponse.swift
  NADA-iOS-forRelease/Sources/NetworkService/Update/UpdateAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Update/UpdateService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Home/VC/HomeViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Home/View/BannerCollectionViewCell.swift
Labels: Yijoon 🐨, Feat

#606 feat: 받은 태그 뷰에서 UISheetPresentationController 적용하여 바텀시트 구현 (#602)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnFire.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnFire.imageset/icnFire.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnFire.imageset/icnFire@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnFire.imageset/icnFire@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnFireDark.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnFireDark.imageset/icnFireDark.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnFireDark.imageset/icnFireDark@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnFireDark.imageset/icnFireDark@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHeart.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHeart.imageset/icnHeart.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHeart.imageset/icnHeart@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHeart.imageset/icnHeart@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHeartDark.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHeartDark.imageset/icnHeartDark.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHeartDark.imageset/icnHeartDark@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHeartDark.imageset/icnHeartDark@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnLabel.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnLabel.imageset/icnLabel.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnLabel.imageset/icnLabel@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnLabel.imageset/icnLabel@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnLabelDark.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnLabelDark.imageset/icnLabelDark.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnLabelDark.imageset/icnLabelDark@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnLabelDark.imageset/icnLabelDark@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnNote.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnNote.imageset/icnNote.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnNote.imageset/icnNote@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnNote.imageset/icnNote@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSmile.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSmile.imageset/icnSmile.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSmile.imageset/icnSmile@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSmile.imageset/icnSmile@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSmileDark.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSmileDark.imageset/icnSmileDark.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSmileDark.imageset/icnSmileDark@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSmileDark.imageset/icnSmileDark@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSun.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSun.imageset/icnSun.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSun.imageset/icnSun@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSun.imageset/icnSun@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSunDark.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSunDark.imageset/icnSunDark.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSunDark.imageset/icnSunDark@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSunDark.imageset/icnSunDark@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconBottomSheet.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconBottomSheet.imageset/iconBottomSheet.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconBottomSheet.imageset/iconBottomSheet@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconBottomSheet.imageset/iconBottomSheet@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconTag.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconTag.imageset/iconTag.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconTag.imageset/iconTag@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconTag.imageset/iconTag@3x.png
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/CardCell/MainCardCell.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/PresentationSheet/FetchTagSheetVC.swift
  Podfile.lock
Labels: Hyungyu 🐯, Feat

#615 feat: 받은 태그 조회 API 구현 (#609)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnFire.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnFire.imageset/icnFireDark.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnFire.imageset/icnFireDark@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnFire.imageset/icnFireDark@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnFireDark.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHeart.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHeart.imageset/icnHeartDark.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHeart.imageset/icnHeartDark@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHeart.imageset/icnHeartDark@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnHeartDark.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnLabel.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnLabel.imageset/icnLabelDark.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnLabel.imageset/icnLabelDark@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnLabel.imageset/icnLabelDark@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnLabelDark.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnNote.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnNote.imageset/icnNote 1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnNote.imageset/icnNote@2x 1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnNote.imageset/icnNote@3x 1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSmile.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSmile.imageset/icnSmileDark.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSmile.imageset/icnSmileDark@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSmile.imageset/icnSmileDark@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSmileDark.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSun.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSun.imageset/icnSunDark.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSun.imageset/icnSunDark@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSun.imageset/icnSunDark@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnSunDark.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnTagCheck.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnTagCheck.imageset/icnTagCheck.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnTagCheck.imageset/icnTagCheck@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnTagCheck.imageset/icnTagCheck@3x.png
  NADA-iOS-forRelease/Sources/Cells/Tag/TagCVC.swift
  NADA-iOS-forRelease/Sources/NetworkModel/NetworkResult.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Tag/CreationTagRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Tag/ReceivedTag.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Tag/Tag.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Tag/TagDeletionRequest.swift
  NADA-iOS-forRelease/Sources/NetworkService/BasicAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Tag/TagAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Tag/TagService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Tag/FetchTagSheetVC.swift
Labels: Hyungyu 🐯, Feat

#619 fix: 랜덤밸런스 API 수정 (#618)
  IntentsExtension/IntentHandler.swift
  NADA-iOS-forRelease/Resouces/Constants/URL.swift
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupService.swift
  NADA-iOS-forRelease/Sources/NetworkService/Nearby/NearbyService.swift
  NADA-iOS-forRelease/Sources/NetworkService/Update/UpdateService.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserSevice.swift
  NADA-iOS-forRelease/Sources/NetworkService/Util/UtilService.swift
  Widgets/WidgetsBundle/MyCardWidget.swift
Labels: Hyungyu 🐯, P1 / Priority High, Fix

#623 feat: 태그 보내기 뷰 구현 (#616)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnOptionCheck.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnOptionCheck.imageset/icnOptionCheck.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnOptionCheck.imageset/icnOptionCheck@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnOptionCheck.imageset/icnOptionCheck@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCheckDone.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCheckDone.imageset/imgCheckDone.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCheckDone.imageset/imgCheckDone@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCheckDone.imageset/imgCheckDone@3x.png
  NADA-iOS-forRelease/Resouces/Extensions/UIColor+Extension.swift
  NADA-iOS-forRelease/Sources/Cells/Tag/SendTagCVC.swift
  NADA-iOS-forRelease/Sources/Cells/Tag/TagCVC.swift
  NADA-iOS-forRelease/Sources/Model/CustomDetent.swift
  NADA-iOS-forRelease/Sources/NetworkModel/GenericResponse.swift
  NADA-iOS-forRelease/Sources/NetworkService/BasicAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Tag/TagAPI.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Tag/FetchTagSheetVC.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Tag/SendTagSheetVC.swift
Labels: Hyungyu 🐯, Feat

#624 feat: 태그 삭제 API 구현 (#614)
  NADA-iOS-forRelease/Sources/NetworkModel/Tag/TagDeletionRequest.swift
  NADA-iOS-forRelease/Sources/NetworkService/Tag/TagAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Tag/TagService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Tag/FetchTagSheetVC.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Tag/SendTagSheetVC.swift
Labels: Hyungyu 🐯, Feat

#626 fix: 받은 태그 뷰에 DiffableDataSource 적용 (#621)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Sources/Model/Section.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Tag/ReceivedTag.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Tag/FetchTagSheetVC.swift
Labels: Hyungyu 🐯, Fix

#631 fix: api path 오탈자 수정 (#630)
  NADA-iOS-forRelease/Sources/NetworkService/Card/CardService.swift
  NADA-iOS-forRelease/Sources/NetworkService/Tag/TagService.swift
Labels: Hyungyu 🐯, Fix

#634 fix: 2차 메인화면 QA (#629)
  NADA-iOS-forRelease/Info.plist
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconArrowRight.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconArrowRight.imageset/icon_arrow_right.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconArrowRight.imageset/icon_arrow_right@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconArrowRight.imageset/icon_arrow_right@3x.png
  NADA-iOS-forRelease/Resouces/Extensions/UILabel+Extension.swift
  NADA-iOS-forRelease/Sources/AppDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Home/VC/HomeViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Home/View/BannerCollectionViewCell.swift
Labels: Yijoon 🐨, QA

#638 fix: 태그 보내기 UI 변경 (#633)
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
  NADA-iOS-forRelease/Sources/Model/CustomDetent.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Tag/SendTagSheetVC.swift
Labels: Hyungyu 🐯, Fix

#639 feat: 태그 필터링 API 구현 (#622)
  NADA-iOS-forRelease/Sources/NetworkService/Tag/TagAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Tag/TagService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Tag/SendTagSheetVC.swift
Labels: Hyungyu 🐯, Feat

#640 feat: 태그 스토리보드 수정 (#635)
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnInformation.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnInformation.imageset/icnInformation.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnInformation.imageset/icnInformation@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnInformation.imageset/icnInformation@3x.png
  NADA-iOS-forRelease/Resouces/Storyboards/CardDetail/CardDetail.storyboard
  NADA-iOS-forRelease/Sources/NetworkService/Tag/TagAPI.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
Labels: Yijoon 🐨, Feat

#641 feat: 태그 보내기 뷰 연결 (#636)
  NADA-iOS-forRelease/Sources/NetworkService/Tag/TagAPI.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Tag/FetchTagSheetVC.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Tag/SendTagSheetVC.swift
Labels: Hyungyu 🐯, Feat

#645 design: grabber 다크모드 이미지 에셋 추가 (#644)
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconBottomSheet.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconBottomSheet.imageset/iconBottomSheet 1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconBottomSheet.imageset/iconBottomSheet@2x 1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconBottomSheet.imageset/iconBottomSheet@3x 1.png
Labels: Hyungyu 🐯, Design

#648 fix: foreground 에서 apns 수신 (#647)
  NADA-iOS-forRelease/Sources/AppDelegate.swift
Labels: Hyungyu 🐯, Fix, QA

#649 feat: 태그 보내기 후에 받은 태그 새로고침 (#642)
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Tag/SendTagSheetVC.swift
Labels: Hyungyu 🐯, Feat, QA

#650 feat: 받은 태그 바텀시트에서 엠티뷰 추가 (#646)
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgSendTagEmpty.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgSendTagEmpty.imageset/imgSendTagEmpty 1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgSendTagEmpty.imageset/imgSendTagEmpty.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgSendTagEmpty.imageset/imgSendTagEmpty@2x 1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgSendTagEmpty.imageset/imgSendTagEmpty@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgSendTagEmpty.imageset/imgSendTagEmpty@3x 1.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgSendTagEmpty.imageset/imgSendTagEmpty@3x.png
  NADA-iOS-forRelease/Sources/ViewControllers/Tag/FetchTagSheetVC.swift
Labels: Hyungyu 🐯, Feat, QA
