Repository TeamNADA/NADA-iOS-ForRelease, pull requests merged in 2023-01, with the labels that each got.

#332 chore: fastlane 자동배포를 위한 certificate 와 signing 설정 (#331)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
Labels: Hyungyu 🐯, P1 / Priority High, Chore

#337 fix: 명함생성뷰 생년월일 피커뷰에서 년도 삭제 (#335)
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectBirthBottomViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift
Labels: Hyungyu 🐯, Fix

#340 chore: fastlane 자동 배포 설정 (#339)
  Gemfile
  Gemfile.lock
  Matchfile
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  fastlane/Appfile
  fastlane/Deliverfile
  fastlane/Fastfile
Labels: Yijoon 🐨, Chore

#341 feat: 앱 내에서 동적링크 생성 (#338)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/NADA-iOS-forRelease.entitlements
  NADA-iOS-forRelease/Resouces/Constants/URL.swift
  NADA-iOS-forRelease/Resouces/GoogleService-Info.plist
  NADA-iOS-forRelease/Sources/AppDelegate.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardShareBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectBirthBottomViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/QRScanViewController.swift
  Podfile
  Podfile.lock
Labels: Hyungyu 🐯, Feat

#344 feat: 네트워크 연결 손실 시 경고 알림창 구현 (#323)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Extensions/UIApplication+Extension.swift
  NADA-iOS-forRelease/Sources/NetworkService/Plugin/MoyaLoggerPlugin.swift
Labels: Hyungyu 🐯, Feat

#346 add: any,dark/card 색상 추가 (#345)
  NADA-iOS-forRelease/Resouces/Assets/Colors.xcassets/card.colorset/Contents.json
  NADA-iOS-forRelease/Resouces/Extensions/UIColor+Extension.swift
Labels: Hyungyu 🐯, Add

#348 add: Lottie CocoaPods 설치 및 근처 명함 json 파일 추가 (#347)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Constants/Lottie.swift
  NADA-iOS-forRelease/Resouces/Lottie/nearby.json
  Podfile
  Podfile.lock
Labels: Hyungyu 🐯, Add

#343 fix: SelectBirthBottomViewController 에서 피커뷰 변경 (#336)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectBirthBottomViewController.swift
Labels: Hyungyu 🐯, Fix

#350 fix: 명함 공유 뷰 수정 (#349)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnNearbyOff.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnNearbyOff.imageset/icnNearbyOff.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnNearbyOff.imageset/icnNearbyOff@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnNearbyOff.imageset/icnNearbyOff@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnNearbyOn.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnNearbyOn.imageset/icnNearbyOn.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnNearbyOn.imageset/icnNearbyOn@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnNearbyOn.imageset/icnNearbyOn@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/nadaLogoTxt.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/nadaLogoTxt.imageset/nadaLogoTxt.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/nadaLogoTxt.imageset/nadaLogoTxt@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/nadaLogoTxt.imageset/nadaLogoTxt@3x.png
  NADA-iOS-forRelease/Resouces/Extensions/UIView+Extension.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardShareBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
  Podfile
  Podfile.lock
Labels: Hyungyu 🐯, Fix

#352 fix: 기본 명함 생성 뷰 수정 (#351)
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.xib
  NADA-iOS-forRelease/Sources/NetworkModel/Card/CardCreationRequest.swift
  NADA-iOS-forRelease/Sources/Protocols/CardCreation/FrontCardCreationDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationViewController.swift
Labels: Hyungyu 🐯, Fix

#354 fix: 기본 명함 앞면 수정 (#353)
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconBirthday.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconBirthday.imageset/iconBirthday.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconBirthday.imageset/iconBirthday@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconBirthday.imageset/iconBirthday@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconMbti.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconMbti.imageset/iconMbti.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconMbti.imageset/iconMbti@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/iconMbti.imageset/iconMbti@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/phoneEnabled.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/phoneEnabled.imageset/phoneEnabled.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/phoneEnabled.imageset/phoneEnabled@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/phoneEnabled.imageset/phoneEnabled@3x.png
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.xib
  NADA-iOS-forRelease/Sources/NetworkModel/Card/Card.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/TeamNADA/TeamNADAViewController.swift
Labels: Hyungyu 🐯, Fix

#356 bug: CardInGroupCollectionViewCell 에서 이미지뷰의 이미지 삭제 (#355)
  NADA-iOS-forRelease/Sources/Cells/GroupCell/CardInGroupCollectionViewCell.xib
Labels: Hyungyu 🐯, bug
