Repository TeamNADA/NADA-iOS-ForRelease, pull requests merged in 2023-05, with the labels that each got.

#456 feat: 명함 그룹 관련 API 연결 #434
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Sources/Factory/ModuleFactory.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Group/GroupAddRequest.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupService.swift
  NADA-iOS-forRelease/Sources/ViewControllers/AroundMe/VC/AroundMeViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardResultBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/VC/GroupEditViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/ViewModel/GroupEditViewModel.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Home/VC/HomeViewController.swift
Labels: Yijoon 🐨, Feat

#476 fix: 명함만들기 뷰 아이콘 크기 수정 (#471)
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/VC/CardCreationCategoryViewController.swift
Labels: Hyungyu 🐯, Fix, QA

#480 fix: 명함 앞면 url 줄 수 변경 (#475)
  NADA-iOS-forRelease/Sources/Cells/CardCell/CompanyFrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/CompanyFrontCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/CardCell/FanFrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FanFrontCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.xib
Labels: Hyungyu 🐯, Fix, QA

#484 fix: 온보딩 로티 매번 스크롤마다 재생으로 수정 (#483)
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Sources/Cells/Onboarding/OnboardingCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Onboarding/OnboardingViewController.swift
Labels: Hyungyu 🐯, Fix, QA

#486 chore: 다크모드 명함만들기 뷰 이미지 에셋 수정 (#485)
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnBasic.imageset/icnBasicDark.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnBasic.imageset/icnBasicDark@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnBasic.imageset/icnBasicDark@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnFan.imageset/icnFanDark.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnFan.imageset/icnFanDark@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnFan.imageset/icnFanDark@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnOffice.imageset/icnOfficeDark.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnOffice.imageset/icnOfficeDark@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/icnOffice.imageset/icnOfficeDark@3x.png
Labels: Hyungyu 🐯, Chore, QA

#477 fix: 명함 뒷면 tmi 폰트 색상 변경 (#472)
  NADA-iOS-forRelease/Sources/Cells/CardCell/BackCardCell.swift
Labels: Hyungyu 🐯, Fix, QA

#478 fix: 바텀시트 내려가는 속도 조절 (#473)
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CommonBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/GroupNameEditBottomSheetViewController.swift
Labels: Hyungyu 🐯, Fix, QA

#482 fix: 명함 앞면으로 다시금 뒤집을 때 선택사항 아이콘이 노출 수정 (#481)
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
Labels: Hyungyu 🐯, Fix, QA

#491 fix: 다크 모드 시에 문구 삭제 (#474)
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupAPI.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/VC/CardCreationCategoryViewController.swift
Labels: Hyungyu 🐯, Fix, QA

#492 feat: 위젯 통해서 앱 열기 (#470)
  IntentsExtension/IntentHandler.swift
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease.xcodeproj/xcshareddata/xcschemes/IntentsExtension.xcscheme
  NADA-iOS-forRelease.xcodeproj/xcshareddata/xcschemes/IntentsExtensionUI.xcscheme
  NADA-iOS-forRelease.xcodeproj/xcshareddata/xcschemes/NADA-iOS-forRelease (Beta).xcscheme
  NADA-iOS-forRelease.xcodeproj/xcshareddata/xcschemes/NADA-iOS-forRelease (Release).xcscheme
  NADA-iOS-forRelease.xcodeproj/xcshareddata/xcschemes/NADA-iOS-forRelease.xcscheme
  NADA-iOS-forRelease.xcodeproj/xcshareddata/xcschemes/WidgetsExtension.xcscheme
  NADA-iOS-forRelease/Info.plist
  NADA-iOS-forRelease/Resouces/Constants/UserDefaults.swift
  NADA-iOS-forRelease/Resouces/Extensions/UserDefaults+Extension.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Home/VC/HomeViewController.swift
  Podfile.lock
  Widgets/Resource/Widgets.intentdefinition
  Widgets/WidgetsBundle/MyCardWidget.swift
Labels: Hyungyu 🐯, 🚨review required🚨, Feat

#495 chore: 내 명함 위젯 엠티뷰 수정 (#494)
  Widgets/Resource/Assets.xcassets/widgetEmpty.imageset/Contents.json
  Widgets/Resource/Assets.xcassets/widgetEmpty.imageset/widgetEmpty.png
  Widgets/Resource/Assets.xcassets/widgetEmpty.imageset/widgetEmpty@2x.png
  Widgets/Resource/Assets.xcassets/widgetEmpty.imageset/widgetEmpty@3x.png
Labels: Hyungyu 🐯, Chore, QA

#497 design: tmi 텍스트 필드 패딩 수정 (#496)
  NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCollectionViewCell.swift
Labels: Hyungyu 🐯, Design, QA

#513 feat: 위젯 타겟을 15.0으로 낮추고 대응하기(#512)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  Widgets/WidgetsBundle/OpenAppLockScreenWidget.swift
  Widgets/WidgetsBundle/QRCodeWidget.swift
  Widgets/WidgetsBundle/WidgetsBundle.swift
  Widgets/WidgetsBundle/WidgetsLiveActivity.swift
Labels: Hyungyu 🐯, Feat, QA

#518 feat: 내 명함 위젯에게 새로운 timeline 요청 (#515)
  IntentsExtension/IntentHandler.swift
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
  Podfile.lock
  Widgets/Resource/Widgets.intentdefinition
  Widgets/WidgetsBundle/MyCardWidget.swift
  Widgets/WidgetsExtension.entitlements
Labels: Hyungyu 🐯, Feat

#519 feat: 내 명함 위젯의 기본값 갱신 구현(#514)
  IntentsExtension/IntentHandler.swift
  Widgets/WidgetsBundle/MyCardWidget.swift
Labels: Hyungyu 🐯, Feat

#521 chore: 기본 명함 배경 이미지 에셋 변경 (#520)
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCardBg01.imageset/imgCardBg01.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCardBg01.imageset/imgCardBg01@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCardBg01.imageset/imgCardBg01@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCardBg02.imageset/imgCardBg02.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCardBg02.imageset/imgCardBg02@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCardBg02.imageset/imgCardBg02@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCardBg03.imageset/imgCardBg03.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCardBg03.imageset/imgCardBg03@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCardBg03.imageset/imgCardBg03@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCardBg04.imageset/imgCardBg04.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCardBg04.imageset/imgCardBg04@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCardBg04.imageset/imgCardBg04@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCardBg05.imageset/imgCardBg05.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCardBg05.imageset/imgCardBg05@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCardBg05.imageset/imgCardBg05@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCardBg06.imageset/imgCardBg06.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCardBg06.imageset/imgCardBg06@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCardBg06.imageset/imgCardBg06@3x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCardBg07.imageset/imgCardBg07.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCardBg07.imageset/imgCardBg07@2x.png
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgCardBg07.imageset/imgCardBg07@3x.png
Labels: Hyungyu 🐯, Chore

#522 fix: 2차 QA 수정 사항 #501
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Info.plist
  NADA-iOS-forRelease/Resouces/Constants/Notification.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Util/HarmonyResponse.swift
  NADA-iOS-forRelease/Sources/NetworkService/Group/GroupAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/Util/UtilAPI.swift
  NADA-iOS-forRelease/Sources/ViewControllers/AroundMe/VC/AroundMeViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/ReceiveCardBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/NewCardHarmonyViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Home/VC/HomeViewController.swift
Labels: Yijoon 🐨, Fix, QA

#524 feat: 로그인했지만 대표 명함이 없을 때 엠티뷰 보여주기 (#523)
  Widgets/WidgetsBundle/MyCardWidget.swift
Labels: Hyungyu 🐯, Feat

#526 feat: 로그아웃된 상태에서는 내 명함 위젯으로 앱 들어와도 바텀시트막기 (#525)
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Home/VC/HomeViewController.swift
Labels: Hyungyu 🐯, Feat

#530 design: 명함 리스트 엠티뷰 문구 및 명함 미리보기뷰 문구 수정 (#528)
  NADA-iOS-forRelease/Resouces/Storyboards/CardCreation/CardCreationPreview.storyboard
  NADA-iOS-forRelease/Sources/Cells/CardCell/EmptyCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/CardList/EmptyCardListTableViewCell.xib
Labels: Hyungyu 🐯, Design, QA

#531 fix: 네트워크 실패에 명함 공유 바텀시트 띄우지 않도록 하기 (#529)
  NADA-iOS-forRelease/Sources/ViewControllers/Home/VC/HomeViewController.swift
Labels: Hyungyu 🐯, Fix, QA

#533 chore: firebase 활용한 동적링크 도메인 및 GoogleService-Info 수정 (#532)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/NADA-iOS-forRelease.entitlements
  NADA-iOS-forRelease/Resouces/Constants/URL.swift
  NADA-iOS-forRelease/Resouces/GoogleService-Info.plist
Labels: Hyungyu 🐯, Chore, QA

#534 feat: 로그인 시 fcm 디바이스 토큰 API 에 전달하기 (#527)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Info.plist
  NADA-iOS-forRelease/NADA-iOS-forRelease.entitlements
  NADA-iOS-forRelease/Resouces/Constants/UserDefaults.swift
  NADA-iOS-forRelease/Sources/AppDelegate.swift
  NADA-iOS-forRelease/Sources/NetworkModel/User/UserLoginRequest.swift
  NADA-iOS-forRelease/Sources/NetworkModel/User/UserWithTokenRequest 2.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserAPI.swift
  NADA-iOS-forRelease/Sources/NetworkService/User/UserSevice.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
  Podfile
  Podfile.lock
Labels: Hyungyu 🐯, Feat, QA

#536 feat: 내 근처의 명함 로딩 뷰 추가 (#535)
  NADA-iOS-forRelease/Sources/ViewControllers/AroundMe/VC/AroundMeViewController.swift
Labels: Yijoon 🐨, Feat

#539 feat: 위젯 기본값 IntentHandler 에서 설정 (#538)
  IntentsExtension/IntentHandler.swift
  Widgets/WidgetsBundle/MyCardWidget.swift
Labels: Hyungyu 🐯, Feat, QA

#537 feat: ga 세팅 및 온보딩 트래킹 (#516)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Info.plist
  NADA-iOS-forRelease/Resouces/Tracking/Event.swift
  NADA-iOS-forRelease/Resouces/Tracking/Screen.swift
  NADA-iOS-forRelease/Resouces/Tracking/Tracking.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Login/LoginViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Onboarding/OnboardingViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Splash/SplashViewController.swift
Labels: Hyungyu 🐯, Feat

#540 feat: 마이페이지 트래킹 (#517)
  NADA-iOS-forRelease/Resouces/Tracking/Event.swift
  NADA-iOS-forRelease/Resouces/Tracking/Screen.swift
  NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
Labels: Hyungyu 🐯, Feat

#544 feat: 위젯으로 앱 접근 시 화면 트래킹 (#541)
  NADA-iOS-forRelease/Resouces/Tracking/Screen.swift
  NADA-iOS-forRelease/Sources/SceneDelegate.swift
Labels: Hyungyu 🐯, Feat

#545 feat: 내 명함 트래킹 (#542)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Tracking/Event.swift
  NADA-iOS-forRelease/Resouces/Tracking/Screen.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/CompanyFrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FanFrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/MainCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/BackCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/CompanyFrontCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FanFrontCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Cells/CreationCard/FrontCardCreationCollectionViewCell.swift
  NADA-iOS-forRelease/Sources/Model/CardContext.swift
  NADA-iOS-forRelease/Sources/Model/CardType.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Card/Taste.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardShareBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/VC/CardCreationCategoryViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/VC/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/VC/CardCreationViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/VC/CompanyCardCreationViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/VC/FanCardCreationViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardList/CardListViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Main/FrontViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
Labels: Hyungyu 🐯, Feat

#548 fix: baseURL 변경에 따른 수정 (#547)
  NADA-iOS-forRelease/Resouces/Constants/URL.swift
Labels: Hyungyu 🐯, Fix

#549 feat: TeamNada뷰 수정 (#511)
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgDa.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgDa.imageset/imgDa 1.jpeg
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgDa.imageset/imgDa 2.jpeg
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgDa.imageset/imgDa.jpeg
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgYoung.imageset/Contents.json
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgYoung.imageset/imgYoung 1.jpg
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgYoung.imageset/imgYoung 2.jpg
  NADA-iOS-forRelease/Resouces/Assets/Assets.xcassets/imgYoung.imageset/imgYoung.jpg
  NADA-iOS-forRelease/Sources/ViewControllers/TeamNADA/TeamNADAViewController.swift
Labels: Hyungyu 🐯, Feat

#551 fix: 동적링크 웹주소 수정 (#550)
  NADA-iOS-forRelease/Resouces/Constants/URL.swift
Labels: Hyungyu 🐯, Fix

#553 fix: GA 트래킹 이름 띄어쓰기 수정 (#552)
  NADA-iOS-forRelease/Resouces/Tracking/Event.swift
  NADA-iOS-forRelease/Resouces/Tracking/Screen.swift
Labels: Hyungyu 🐯, Fix

#557 fix: 엠티뷰 문구 수정 및 명함 생성 문구 수정 (#554)
  NADA-iOS-forRelease/Sources/Cells/CardCell/EmptyCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/CardList/EmptyCardListTableViewCell.xib
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/VC/CardCreationViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/VC/CompanyCardCreationViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/VC/FanCardCreationViewController.swift
Labels: Hyungyu 🐯, Fix, QA

#562 fix: 회원탈퇴 문구 수정 (#561)
  NADA-iOS-forRelease/Sources/ViewControllers/More/MoreViewController.swift
Labels: Hyungyu 🐯, Fix, QA

#563 fix: 명함 라운드값 수정 (#555)
  NADA-iOS-forRelease/Sources/Cells/CardCell/CompanyFrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/CompanyFrontCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/CardCell/FanFrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FanFrontCardCell.xib
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.xib
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardResultBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
Labels: Hyungyu 🐯, Fix, QA

#558 feat: 그룹 트래킹 (#543)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Storyboards/CardDetail/CardDetail.storyboard
  NADA-iOS-forRelease/Resouces/Tracking/Event.swift
  NADA-iOS-forRelease/Resouces/Tracking/Screen.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/CompanyFrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FanFrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/Model/CardContext.swift
  NADA-iOS-forRelease/Sources/ViewControllers/AroundMe/VC/AroundMeViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/AddWithIdBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/CardResultBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/ReceiveCardBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/BottomSheet/SelectGroupBottomSheetViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/GroupViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Group/QRScanViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/GroupEdit/VC/GroupEditViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Home/VC/HomeViewController.swift
Labels: Yijoon 🐨, Feat

#566 fix: 변수명 오류 해결 (#565)
  NADA-iOS-forRelease.xcodeproj/xcshareddata/xcschemes/NADA-iOS-forRelease (Beta).xcscheme
  NADA-iOS-forRelease.xcodeproj/xcshareddata/xcschemes/NADA-iOS-forRelease.xcscheme
  NADA-iOS-forRelease/Info.plist
  NADA-iOS-forRelease/Resouces/Constants/URL.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/CompanyFrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FanFrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  Widgets/Resource/Widgets.intentdefinition
Labels: Yijoon 🐨, Fix, QA

#564 feat: 스플래시 뷰에 로티 추가 (#556)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Resouces/Constants/Lottie.swift
  NADA-iOS-forRelease/Resouces/Lottie/nada_logo_motion.json
  NADA-iOS-forRelease/Resouces/Storyboards/Splash/Splash.storyboard
  NADA-iOS-forRelease/Sources/Cells/CardCell/CompanyFrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FanFrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/ViewControllers/Splash/SplashViewController.swift
Labels: Hyungyu 🐯, Feat

#568 fix: 4차 QA 수정 (#567)
  NADA-iOS-forRelease.xcodeproj/project.pbxproj
  NADA-iOS-forRelease/Sources/Cells/CardCell/CompanyFrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FanFrontCardCell.swift
  NADA-iOS-forRelease/Sources/Cells/CardCell/FrontCardCell.swift
  NADA-iOS-forRelease/Sources/NetworkModel/Util/HarmonyResponse.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/CardDetailViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardDetail/NewCardHarmonyViewController.swift
Labels: Yijoon 🐨, Fix, QA

#570 fix: 명함 생성, 미리보기 버튼 폰트 적용 (#569)
  NADA-iOS-forRelease/Resouces/Storyboards/CardCreation/CardCreation.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/CardCreation/CardCreationPreview.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/CardCreation/CompanyCardCreation.storyboard
  NADA-iOS-forRelease/Resouces/Storyboards/CardCreation/FanCardCreation.storyboard
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/VC/CardCreationPreviewViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/VC/CardCreationViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/VC/CompanyCardCreationViewController.swift
  NADA-iOS-forRelease/Sources/ViewControllers/CardCreation/VC/FanCardCreationViewController.swift
Labels: Hyungyu 🐯, Fix, QA
